export default function () {
  this.transition(
    this.fromRoute('index'),
    this.toRoute('about'),
    this.use('toLeft')
  );
  this.transition(
    this.fromRoute('about'),
    this.toRoute('index'),
    this.use('toRight')
  );
  this.transition(
    this.fromRoute('index'),
    this.toRoute('portfolio'),
    this.use('toLeft')
  );
  this.transition(
    this.fromRoute('about'),
    this.toRoute('portfolio'),
    this.use('toLeft')
  );
  this.transition(
    this.fromRoute('portfolio'),
    this.toRoute('about'),
    this.use('toRight')
  );
  this.transition(
    this.fromRoute('index'),
    this.toRoute('embersite'),
    this.use('toUp')
  );
  this.transition(
    this.fromRoute('about'),
    this.toRoute('embersite'),
    this.use('toUp')
  );
  this.transition(
    this.fromRoute('portfolio'),
    this.toRoute('embersite'),
    this.use('toUp')
  );
  this.transition(
    this.fromRoute('portfolio'),
    this.toRoute('index'),
    this.use('toRight')
  );
  this.transition(
    this.fromRoute('embersite'),
    this.toRoute('index'),
    this.use('toDown')
  );
  this.transition(
    this.fromRoute('embersite'),
    this.toRoute('about'),
    this.use('toDown')
  );
  this.transition(
    this.fromRoute('embersite'),
    this.toRoute('portfolio'),
    this.use('toDown')
  );
}